# action.yml
name: 'Release Management'
author: 'Sachin Shankar'
branding:
  icon: 'git-pull-request'
  color: 'purple'
description: 'Automate the creation of a tag and a new release'
inputs:
  typeOfRelease:
    description: 'Type of Release (major, minor, patch, custom)'
    required: true
    default: 'patch'
    type: choice
    options:
    - major
    - minor
    - patch
    - custom
  version:
    description: 'Version of the release (only for custom release)'
    required: false
    type: string
  releaseNotes:
    description: 'Release notes'
    required: true
    type: string
  generateReleaseNotes:
    description: 'Auto generate release notes'
    required: false
    default: true
    type: boolean
  releaseDraft:
    description: 'Release draft'
    required: false
    default: false
    type: boolean
  preRelease:
    description: 'Pre-release'
    required: false
    default: false
    type: boolean
  targetCommitish:
    description: 'Target commitish'
    required: false
    default: 'main'
    type: string
  githubToken:
    description: 'GitHub Token'
    required: true
    type: string
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
  - ${{ inputs.typeOfRelease }}
  - ${{ inputs.version }}
  - ${{ inputs.releaseNotes }}
  - ${{ inputs.generateReleaseNotes }}
  - ${{ inputs.releaseDraft }}
  - ${{ inputs.preRelease }}
  - ${{ inputs.targetCommitish }}
  - ${{ inputs.githubToken }}
